INSERT INTO public.estados(uf, nome) VALUES ('AC','Acre');
INSERT INTO public.estados(uf, nome) VALUES ('AL','Alagoas');
INSERT INTO public.estados(uf, nome) VALUES ('AM','Amazonas');
INSERT INTO public.estados(uf, nome) VALUES ('AP','Amapá');
INSERT INTO public.estados(uf, nome) VALUES ('BA','Bahia');
INSERT INTO public.estados(uf, nome) VALUES ('CE','Ceará');
INSERT INTO public.estados(uf, nome) VALUES ('DF','Distrito Federal');
INSERT INTO public.estados(uf, nome) VALUES ('ES','Espírito Santo');
INSERT INTO public.estados(uf, nome) VALUES ('GO','Goiás');
INSERT INTO public.estados(uf, nome) VALUES ('MA','Maranhão');
INSERT INTO public.estados(uf, nome) VALUES ('MG','Minas Gerais');
INSERT INTO public.estados(uf, nome) VALUES ('MS','Mato Grosso do Sul');
INSERT INTO public.estados(uf, nome) VALUES ('MT','Mato Grosso');
INSERT INTO public.estados(uf, nome) VALUES ('PA','Pará');
INSERT INTO public.estados(uf, nome) VALUES ('PB','Paraíba');
INSERT INTO public.estados(uf, nome) VALUES ('PE','Pernambuco');
INSERT INTO public.estados(uf, nome) VALUES ('PI','Piauí');
INSERT INTO public.estados(uf, nome) VALUES ('PR','Paraná');
INSERT INTO public.estados(uf, nome) VALUES ('RJ','Rio de Janeiro');
INSERT INTO public.estados(uf, nome) VALUES ('RN','Rio Grande do Norte');
INSERT INTO public.estados(uf, nome) VALUES ('RO','Rondônia');
INSERT INTO public.estados(uf, nome) VALUES ('RR','Roraima');
INSERT INTO public.estados(uf, nome) VALUES ('RS','Rio Grande do Sul');
INSERT INTO public.estados(uf, nome) VALUES ('SC','Santa Catarina');
INSERT INTO public.estados(uf, nome) VALUES ('SE','Sergipe');
INSERT INTO public.estados(uf, nome) VALUES ('SP','São Paulo');
INSERT INTO public.estados(uf, nome) VALUES ('TO','Tocantins');
INSERT INTO public.cidade( nome,   estado_uf) values ('Parajuru','CE');
INSERT INTO public.cidade( nome,   estado_uf) values ('Parambu','CE');
INSERT INTO public.cidade( nome,   estado_uf) values ('Parapui','CE');
INSERT INTO public.cidade( nome,   estado_uf) values ('Acrelandia','AC');
INSERT INTO public.cidade( nome,   estado_uf) values ('Assis Brasil','AC');
INSERT INTO public.cidade( nome,   estado_uf) values ('Cruzeiro do Sul','AC');
INSERT INTO public.cidade( nome,   estado_uf) values ('Epitaciolandia','AC');
INSERT INTO public.cidade( nome,   estado_uf) values ('Apui','AM');
INSERT INTO public.cidade( nome,   estado_uf) values ('Acupe','BA');
INSERT INTO public.cidade( nome,   estado_uf) values ('Agua Doce','BA');
INSERT INTO public.cidade( nome,   estado_uf) values ('Agua Fria','BA');
INSERT INTO public.cidade( nome,   estado_uf) values ('Aguas do Paulista','BA');
INSERT INTO public.cidade( nome,   estado_uf) values ('Aiquara','BA');
INSERT INTO public.cidade( nome,   estado_uf) values ('Central de Santa Helena','MG');
INSERT INTO public.cidade( nome,   estado_uf) values ('Centralina','MG');
INSERT INTO public.cidade( nome,   estado_uf) values ('Cervo','MG');
INSERT INTO public.cidade( nome,   estado_uf) values ('Chacara','MG');
INSERT INTO public.cidade( nome,   estado_uf) values ('Chapada de Minas','MG');
INSERT INTO public.cidade( nome,   estado_uf) values ('Citrolandia','MG');
INSERT INTO public.cidade( nome,   estado_uf) values ('Claro de Minas','MG');
INSERT INTO public.cidade( nome,   estado_uf) values ('Irai','RS');
INSERT INTO public.cidade( nome,   estado_uf) values ('Irui','RS');
INSERT INTO public.cidade( nome,   estado_uf) values ('Itai','RS');
INSERT INTO public.cidade( nome,   estado_uf) values ('Itaimbezinho','RS');
INSERT INTO public.cidade( nome,   estado_uf) values ('Macucos','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Maristela','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Martim Francisco','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Martinho Prado Junior','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Martinopolis','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Matao','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Maua','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Mendonca','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Meridiano','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Presidente Prudente','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Marilia','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Presidente Epitacio','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Presidente Venceslau','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('São Paulo','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Piracicaba','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Campinas','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Americana','SP');
INSERT INTO public.cidade( nome,   estado_uf) values ('Rio de Janeiro','RJ');

INSERT INTO banco(idBanco, nome)	VALUES (1, 'Banco do Brasil');
INSERT INTO banco(idBanco, nome)	VALUES (2, 'Banco Central do Brasil');
INSERT INTO banco(idBanco, nome)	VALUES (3, 'Banco da Amazônia');
INSERT INTO banco(idBanco, nome)	VALUES (4, 'Banco do Nordeste do Brasil');
INSERT INTO banco(idBanco, nome)	VALUES (7, 'Banco Nacional de Desenvolvimento Econômico e Social');
INSERT INTO banco(idBanco, nome)	VALUES (104, 'Caixa Econômica Federal');
INSERT INTO banco(idBanco, nome)	VALUES (46, 'Banco Regional de Desenvolvimento do Extremo Sul');
INSERT INTO banco(idBanco, nome)	VALUES (23, 'Banco de Desenvolvimento de Minas Gerais');
INSERT INTO banco(idBanco, nome)	VALUES (70, 'Banco de Brasília');
INSERT INTO banco(idBanco, nome)	VALUES (47, 'Banco do Estado de Sergipe');
INSERT INTO banco(idBanco, nome)	VALUES (21, 'Banco do Estado do Espírito Santo');
INSERT INTO banco(idBanco, nome)	VALUES (37, 'Banco do Estado do Pará');
INSERT INTO banco(idBanco, nome)	VALUES (41, 'Banco do Estado do Rio Grande do Sul');
INSERT INTO banco(idBanco, nome)	VALUES (75, 'Banco ABN Amro S.A.');
INSERT INTO banco(idBanco, nome)	VALUES (25, 'Banco Alfa');
INSERT INTO banco(idBanco, nome)	VALUES (719, 'Banco Banif');
INSERT INTO banco(idBanco, nome)	VALUES (107, 'Banco BBM');
INSERT INTO banco(idBanco, nome)	VALUES (318, 'Banco BMG');
INSERT INTO banco(idBanco, nome)	VALUES (218, 'Banco Bonsucesso');
INSERT INTO banco(idBanco, nome)	VALUES (208, 'Banco BTG Pactual');
INSERT INTO banco(idBanco, nome)	VALUES (263, 'Banco Cacique');
INSERT INTO banco(idBanco, nome)	VALUES (473, 'Banco Caixa Geral - Brasil');
INSERT INTO banco(idBanco, nome)	VALUES (745, 'Banco Citibank');
INSERT INTO banco(idBanco, nome)	VALUES (721, 'Banco Credibel');
INSERT INTO banco(idBanco, nome)	VALUES (505, 'Banco Credit Suisse');
INSERT INTO banco(idBanco, nome)	VALUES (707, 'Banco Daycoval');
INSERT INTO banco(idBanco, nome)	VALUES (265, 'Banco Fator');
INSERT INTO banco(idBanco, nome)	VALUES (224, 'Banco Fibra');
INSERT INTO banco(idBanco, nome)	VALUES (121, 'Banco Gerador');
INSERT INTO banco(idBanco, nome)	VALUES (612, 'Banco Guanabara');
INSERT INTO banco(idBanco, nome)	VALUES (604, 'Banco Industrial do Brasil');
INSERT INTO banco(idBanco, nome)	VALUES (320, 'Banco Industrial e Comercial');
INSERT INTO banco(idBanco, nome)	VALUES (653, 'Banco Indusval');
INSERT INTO banco(idBanco, nome)	VALUES (77, 'Banco Intermedium');
INSERT INTO banco(idBanco, nome)	VALUES (184, 'Banco Itaú BBA');
INSERT INTO banco(idBanco, nome)	VALUES (479, 'Banco ItaúBank');
INSERT INTO banco(idBanco, nome)	VALUES (389, 'Banco Mercantil do Brasil');
INSERT INTO banco(idBanco, nome)	VALUES (746, 'Banco Modal');
INSERT INTO banco(idBanco, nome)	VALUES (738, 'Banco Morada');
INSERT INTO banco(idBanco, nome)	VALUES (623, 'Banco Pan');
INSERT INTO banco(idBanco, nome)	VALUES (611, 'Banco Paulista');
INSERT INTO banco(idBanco, nome)	VALUES (643, 'Banco Pine');
INSERT INTO banco(idBanco, nome)	VALUES (654, 'Banco Renner');
INSERT INTO banco(idBanco, nome)	VALUES (741, 'Banco Ribeirão Preto');
INSERT INTO banco(idBanco, nome)	VALUES (422, 'Banco Safra');
INSERT INTO banco(idBanco, nome)	VALUES (33, 'Banco Santander');
INSERT INTO banco(idBanco, nome)	VALUES (637, 'Banco Sofisa');
INSERT INTO banco(idBanco, nome)	VALUES (82, 'Banco Topázio');
INSERT INTO banco(idBanco, nome)	VALUES (655, 'Banco Votorantim');
INSERT INTO banco(idBanco, nome)	VALUES (237, 'Bradesco');
INSERT INTO banco(idBanco, nome)	VALUES (341, 'Itaú Unibanco');
INSERT INTO banco(idBanco, nome)	VALUES (756, 'Banco Cooperativo do Brasil - BANCOOB');
INSERT INTO banco(idBanco, nome)	VALUES (748, 'Banco Cooperativo Sicredi - BANSICREDI');
